name="i am yash sharma_1 "
print(len(name))
print(name.endswith("ma"))
print(name.startswith("i"))
print(name.capitalize())
print(name.find("am"))
print(name.replace("yash","yuvansh"))
print(name.title())
print(name.split())
print(name.strip())
print(name.count("a"))
print(name.isdigit())
print(name.isalpha())
print(name.isspace())
print(name.upper())
print(name.lower())
# escape sequence charaters 
print("hello\n{}".format(name))
print("hello\t{}".format(name))
print("hello\"{}\"".format(name))